### ISSUE TITLE
Create diff fetchDocument functions

### ISSUE THREAD

**Issue by PoulavBhowmick03** [PoulavBhowmick03/decentraldocs#37]
Currently we have only issuer fetchDocuments function. But we need different fetchDocuments functions for different USER TYPES

**Comment by SoarinSkySagar** [comment]
@PoulavBhowmick03 koto crypto dibi ei issue ta resolve korle?

**Comment by PoulavBhowmick03** [comment]
> @PoulavBhowmick03 koto crypto dibi ei issue ta resolve korle?

0.001 $DOGE

**Comment by SoarinSkySagar** [comment]
> > @PoulavBhowmick03 koto crypto dibi ei issue ta resolve korle?
> 
> 0.001 $DOGE

sowwy, not interested

**Comment by PoulavBhowmick03** [comment]
> > > @PoulavBhowmick03 koto crypto dibi ei issue ta resolve korle?
> > 
> > 0.001 $DOGE
> 
> sowwy, not interested

Shesh koro eta ar blockchain integration ta
